细节优化

diff --git a/Function/log b/Function/log
--- a/Function/log
+++ b/Function/log
@@ -5,18 +5,18 @@ YELLOW='\033[1;33m'
 BLUE='\033[0;34m'
 NC='\033[0m'
 function log.info(){
-    local timestamp=$(date +"%H:%M:%S")
-    echo -e "${BLUE}[INFO][${timestamp}] - $1${NC}"
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${BLUE}[INFO][${timestamp}] - $1${NC}"
 }
 function log.success(){
-    local timestamp=$(date +"%H:%M:%S")
-    echo -e "${GREEN}[SUCCESS][${timestamp}] - $1${NC}"
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${GREEN}[SUCCESS][${timestamp}] - $1${NC}"
 }
 function log.warn(){
-    local timestamp=$(date +"%H:%M:%S")
-    echo -e "${YELLOW}[WARN][${timestamp}] - $1${NC}"
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${YELLOW}[WARN][${timestamp}] - $1${NC}"
 }
 function log.error(){
-    local timestamp=$(date +"%H:%M:%S")
-    echo -e "${RED}[ERROR][${timestamp}] - $1${NC}" >&2
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${RED}[ERROR][${timestamp}] - $1${NC}" >&2
 }
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,5 @@
 #!/bin/env bash
+#通用颜色变量
 black="\e[30m"
 red="\033[31m"
 green="\033[32m"
@@ -8,29 +9,97 @@ purple="\033[35m"
 cyan="\033[36m"
 white="\033[37m"
 background="\033[0m"
-UseAgreement="
-AstrBot Shell 使用协议
-1.欢迎使用AstrBot Shell 项目（以下简称“本项目”）。在使用本项目之前，请仔细阅读并遵守本协议的所有条款和条件。使用本项目即表示您同意受到本协议的约束。
-2.使用/修改本项目即表示您同意遵守本协议中的所有条款和条件。如果您不同意本协议的任何部分，则不得使用本项目。
-3.本项目是纯免费开源的，不会对您进行任何下载/克隆收费，也不会对您使用任何内容收费。禁止以任何形式出售本项目的内容。如果您的项目中有收款方式，例如众筹平台[爱发电]，请勿调用本项目的内容。
-4.本项目允许您对您设备上已下载的本项目文件进行本地修改，以满足您的需求。但请勿在获得本项目作者(ArcticFox520)同意之前，在包括但不限于Gitee、GitHub、GitLab、OSChina等其他源代码交流平台，QQ、微信、Discord、Telegram等其他社交媒体平台，阿里云盘，百度网盘，123盘等网络存储平台，上传播修改后的版本。
-5.本项目的用户协议同样适用于本项目作者(ArcticFox520)提供的其他项目。
-6.本项目不承担任何由用户使用本项目所产生的直接或间接的责任。未经本项目作者(ArcticFox520)的明确授权，任何人不得将本项目用于商业目的。
-7.您可以在遵守本协议的前提下，自由地使用、修改本项目的内容。但您需要承担因您的使用、修改本项目内容而产生的任何问题和责任。
-8.如果您在使用本项目时遇到任何问题或需要帮助，请通过本项目作者(ArcticFox520)提供的联系方式与其取得联系。本项目作者(ArcticFox520)将尽力为您提供帮助和支持。
-9.本项目的用户协议可能会随时更新和修改。继续使用本项目，即表示您同意受到更新和修改后的协议的约束。
-10.对于本项目的最终所有权和解释权归本项目的唯一作者(ArcticFox520)（https://github.com/ArcticFox520）所有。
-最后，感谢您对 AstrBot Shell 项目的信任与支持!"
-echo -e ${blue}[${yellow}*${blue}] ${cyan}请认真阅读 ${yellow}使用协议${background}
-echo
-echo ${UserAgreement}
-echo -en "您是否同意本协议 [Y/N] " && read yn
-if [[ ${yn} != "Y" && ${yn} != "y" ]]
-then
-  exit
-fi
+#日志颜色变量
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+NC='\033[0m'
+#Github 镜像
+export GHP="https://gh.arcticfox.top/"
 
-function IncrementCounter(){
+function log.info(){
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${BLUE}[INFO][${timestamp}] - $1${NC}"
+}
+function log.success(){
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${GREEN}[SUCCESS][${timestamp}] - $1${NC}"
+}
+function log.warn(){
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${YELLOW}[WARN][${timestamp}] - $1${NC}"
+}
+function log.error(){
+  local timestamp=$(date +"%H:%M:%S")
+  echo -e "${RED}[ERROR][${timestamp}] - $1${NC}" >&2
+}
+
+function selectLocation(){
+if [ -n "${LOCATION}" ]; then
+    return 0
+fi
+echo
+cat << FOX
+ ———————————————————
+ ${cyan}请问您的设备所在位置是? 
+    ${green}1${white}. 中国大陆 ${background}
+    ${green}2${white}. 其他位置 ${background}
+ ———————————————————
+FOX
+echo -en " "${cyan}请输入数字 ${white}[1-2]: ${background}
+read num
+case "${num}" in
+  1)
+    export LOCATION=CN
+    return 0
+    ;;
+  2)
+    return 1
+    ;;
+  *)
+    log.warn "输入错误 保持默认 中国大陆"
+    return 0
+    ;;
+esac
+}
+function getLocation(){
+if [ -x "$(command -v jq)" ]
+then
+  ApiList=(
+    "ipinfo.io/json .country"
+    "ipapi.co/json .country"
+    "ip-api.com/json .countryCode"
+  )
+  for i in ${ApiList[@]}
+  do
+    local Api=$(echo ${i} | awk '{print $1}')
+    local field=$(echo ${i} | awk '{print $2}')
+    local result=$(curl -sL --connect-timeout 5 --max-time 10 ${Api})
+    if echo "${result}" | jq -r ${field} | grep -q "CN";then
+      return 0
+    else
+      return 1
+    fi
+  done
+else
+  ApiList=(
+    "ipinfo.io/country"
+    "ipapi.co/country"
+  )
+  for i in ${ApiList[@]}
+  do
+    local result=$(curl -sL --connect-timeout 5 --max-time 10 ${i})
+    if echo "${result}" | grep -q "CN";then
+      return 0
+    else
+      return 1
+    fi
+  done
+fi
+}
+
+function IncrCounter(){
   if [ -z ${count} ]
   then
     count=0
@@ -48,51 +117,247 @@ function getFile(){
 file="$1"
 URL="$2"
 Download(){
-  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
+  log.info "正在下载 ${file}"
   until ${Command}
   do
     if ! IncrCounter
     then
-      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
+      log.error "错误次数过多"
       return 1
     fi
-    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
+    log.warn "下载失败 三秒后重试"
     sleep 3s
   done
-  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成${background}
+  log.success "下载完成"
   return 0
 }
-if $(command -v wget > /dev/null 2>&1) && $(wget --help | grep -q show-progress)
+if $(type wget > /dev/null 2>&1) && $(wget --help 2>&1 | grep -q show-progress)
 then
   Command="wget --quiet --show-progress --output-document="${file}" --continue "${URL}""
   Download
-elif $(command -v curl > /dev/null 2>&1) && $(curl --help all | grep -q progress-bar)
+elif $(type curl > /dev/null 2>&1) && $(curl --help all 2>&1 | grep -q progress-bar)
 then
   Command="curl --output "${file}" --progress-bar --location --continue-at - "${URL}""
   Download
-elif $(command -v wget > /dev/null 2>&1)
+elif $(type curl > /dev/null 2>&1)
+then
+  Command="curl --output "${file}" --continue-at - "${URL}""
+  Download
+elif $(type wget > /dev/null 2>&1)
 then
   Command="wget --output-document="${file}" --continue "${URL}""
   Download
 else
-  echo -e ${blue}[${red}*${blue}] ${cyan}无下载器${background}
+  log.error "无下载器"
   return 1
 fi
 }
-function AndroidInstall(){
-  
+
+function gitCR(){
+gitClone(){
+if getLocation
+then
+  if git clone --depth=1 --branch=$1 ${GHP}https://github.com/$2
+  then
+    return 0
+  else
+    return 1
+  fi
+  fi
+else
+  if git clone --depth=1 --branch=$1 https://github.com/$2
+  then
+    return 0
+  else
+    return 1
+  fi
+fi
+}
+gitRelease(){
+if getLocation
+then
+  if getFile $1 ${GHP}https://github.com/$2/releases/latest/download/$3
+  then
+    return 0
+  else
+    return 1
+  fi
+else
+  if getFile $1 https://github.com/$2/releases/latest/download/$3
+  then
+    return 0
+  else
+    return 1
+  fi
+fi
+}
+gitRaw(){
+if getLocation
+then
+  if getFile $1 ${GHP}https://github.com/$2/raw/refs/heads/$3/$4
+  then
+    return 0
+  else
+    return 1
+  fi
+else
+  if getFile $1 ${GHP}https://github.com/$2/raw/refs/heads/$3/$4
+  then
+    return 0
+  else
+    return 1
+  fi
+fi
+}
+case $1 in
+clone)
+  # $2: 分支名
+  # $3: 用户名/仓库名
+  gitClone $2 $3;;
+release)
+  # $2: 保存文件名
+  # $3: 用户名/仓库名
+  # $4: release文件名
+  gitRelease $2 $3 $4;;
+raw)
+  # $2: 保存文件名
+  # $3 用户名/仓库名
+  # $4 分支名
+  # $5 文件路径
+  gitRaw $2 $3 $4 $5;;
+esac
 }
 
+function AdIt(){
+setSourcList(){
+if getLocation
+then
+  echo '
+# The termux repository mirror
+deb https://mirrors.cernet.edu.cn/termux/apt/termux-main/ stable main
+deb https://mirrors.cernet.edu.cn/termux/apt/termux-root/ root stable
+deb https://mirrors.cernet.edu.cn/termux/apt/termux-x11/ x11 main
+' > $PREFIX/etc/apt/sources.list
+else
+  echo '
+# The termux repository
+deb https://packages.termux.dev/apt/termux-main/ stable main
+deb https://packages.termux.dev/apt/termux-root/ root stable
+deb https://packages.termux.dev/apt/termux-x11/ x11 main
+' > $PREFIX/etc/apt/sources.list
+fi
+log.info "正在更新 软件源列表"
+apt -y update
+log.info "更新完成"
+}
+package(){
+Package=("git")
+for PKG in ${Package[@]}
+do
+  if ! dpkg -s ${PKG} > /dev/null 2>&1
+  then
+    setSourcList
+    log.info "正在安装 ${PKG}"
+    until apt install -y ${PKG}
+    do
+      log.warn "安装失败 3秒后重试"
+      sleep 3s
+    done
+    log.success "安装成功"
+  fi
+done
+}
+package
+log.info "正在克隆 AF-Proot"
+if gitClone clone main ArcticFox520/AF-Proot
+then
+  log.success "克隆成功"
+else
+  log.error "克隆失败"
+fi
+gitClone raw install ArcticFox520/AstrBot-Shell main install
+export custom="$HOME/custom"
+bash AF-Proot/run
+exit
+}
 
+function LxIt(){
+setSourcList(){
+if getLocation
+then
+  if grep -iq "ports.ubuntu.com" /etc/apt/sources.list
+  then
+    OldSource="ports.ubuntu.com"
+    NewSource="mirrors.cernet.edu.cn"
+    sed -i "s|${OldSource}|${NewSource}|g" /etc/apt/sources.list
+  fi
+fi
+log.info "正在更新 软件源列表"
+apt -y update
+log.info "更新完成"
+}
+package(){
+Package=("git")
+for PKG in ${Package[@]}
+do
+  if ! dpkg -s ${PKG} > /dev/null 2>&1
+  then
+    setSourcList
+    log.info "正在安装 ${PKG}"
+    until apt install -y ${PKG}
+    do
+      log.warn "安装失败 3秒后重试"
+      sleep 3s
+    done
+    log.success "安装成功"
+  fi
+done
+}
+log.info "正在克隆 AstrBot-Shell"
+if gitClone clone main ArcticFox520/AstrBot-Shell
+then
+  log.success "克隆成功"
+else
+  log.error "克隆失败"
+fi
+bash AstrBot-Shell/run
+}
 
+cat << FOX
+AstrBot Shell 使用协议
+1.欢迎使用AstrBot Shell 项目（以下简称“本项目”）。在使用本项目之前，请仔细阅读并遵守本协议的所有条款和条件。使用本项目即表示您同意受到本协议的约束。
+2.使用/修改本项目即表示您同意遵守本协议中的所有条款和条件。如果您不同意本协议的任何部分，则不得使用本项目。
+3.本项目是纯免费开源的，不会对您进行任何下载/克隆收费，也不会对您使用任何内容收费。禁止以任何形式出售本项目的内容。如果您的项目中有收款方式，例如众筹平台[爱发电]，请勿调用本项目的内容。
+4.本项目允许您对您设备上已下载的本项目文件进行本地修改，以满足您的需求。但请勿在获得本项目作者(ArcticFox520)同意之前，在包括但不限于Gitee、GitHub、GitLab、OSChina等其他源代码交流平台，QQ、微信、Discord、Telegram等其他社交媒体平台，阿里云盘，百度网盘，123盘等网络存储平台，上传播修改后的版本。
+5.本项目的用户协议同样适用于本项目作者(ArcticFox520)提供的其他项目。
+6.本项目不承担任何由用户使用本项目所产生的直接或间接的责任。未经本项目作者(ArcticFox520)的明确授权，任何人不得将本项目用于商业目的。
+7.您可以在遵守本协议的前提下，自由地使用、修改本项目的内容。但您需要承担因您的使用、修改本项目内容而产生的任何问题和责任。
+8.如果您在使用本项目时遇到任何问题或需要帮助，请通过本项目作者(ArcticFox520)提供的联系方式与其取得联系。本项目作者(ArcticFox520)将尽力为您提供帮助和支持。
+9.本项目的用户协议可能会随时更新和修改。继续使用本项目，即表示您同意受到更新和修改后的协议的约束。
+10.对于本项目的最终所有权和解释权归本项目的唯一作者(ArcticFox520)（https://github.com/ArcticFox520）所有。
+最后，感谢您对 AstrBot Shell 项目的信任与支持!
+FOX
+while true; do
+  read -p "您是否同意本协议 [Y/N] " YN
+  case "${YN,,}" in
+    y) break ;;
+    n) echo -e ${blue}[${red}*${blue}] ${cyan}已退出${background} ; exit 0 ;;
+    *) echo -e ${blue}[${yellow}*${blue}] ${cyan}无效输入${background} ;;
+  esac
+done
 
-case $(uname -o)
+case "$(uname -o)" in
 Android)
-  AndroidInstall
+  AdIt
   ;;
 *Linux*)
-  LinuxInstall)
+  if ! grep -iq ubuntu /etc/issue
+  then
+    log.erro "暂不支持您的Linux发行版"
+  fi
+  LxIt
   ;;
+*)
+  log.erro "暂不支持您的系统"
+  exit
 esac
-  
-  
