细节优化

diff --git a/AF-Proot/function b/AF-Proot/function
--- a/AF-Proot/function
+++ b/AF-Proot/function
@@ -8,6 +8,27 @@ purple="\033[35m"
 cyan="\033[36m"
 white="\033[37m"
 background="\033[0m"
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+NC='\033[0m'
+function log.info(){
+    local timestamp=$(date +"%H:%M:%S")
+    echo -e "${BLUE}[INFO][${timestamp}] - $1${NC}"
+}
+function log.success(){
+    local timestamp=$(date +"%H:%M:%S")
+    echo -e "${GREEN}[SUCCESS][${timestamp}] - $1${NC}"
+}
+function log.warn(){
+    local timestamp=$(date +"%H:%M:%S")
+    echo -e "${YELLOW}[WARN][${timestamp}] - $1${NC}"
+}
+function log.error(){
+    local timestamp=$(date +"%H:%M:%S")
+    echo -e "${RED}[ERROR][${timestamp}] - $1${NC}" >&2
+}
 function IncrementCounter(){
   if [ -z ${count} ]
   then
@@ -25,18 +46,18 @@ function getFile(){
 file="$1"
 URL="$2"
 Download(){
-  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
+  log.info "正在下载 ${file}"
   until ${Command}
   do
     if ! IncrCounter
     then
-      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
+      log.error "错误次数过多"
       return 1
     fi
-    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
+    log.warn "下载失败 三秒后重试"
     sleep 3s
   done
-  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成${background}
+  log.success "下载完成"
   return 0
 }
 if $(command -v wget > /dev/null 2>&1) && $(wget --help | grep -q show-progress)
@@ -52,7 +73,7 @@ then
   Command="wget --output-document="${file}" --continue "${URL}""
   Download
 else
-  echo -e ${blue}[${red}*${blue}] ${cyan}无下载器${background}
+  log.error "无下载器"
   return 1
 fi
 }
@@ -73,7 +94,7 @@ case "$num" in
   2)
     return 1;;
   *)
-    echo -e "\n${blue}[${red}*${blue}] ${cyan}输入错误，保持默认：${yellow}中国大陆${background}"
+    log.warn "输入错误 保持默认 中国大陆"
     return 0
 esac
 }
@@ -104,4 +125,21 @@ fi
 selectLocation
 local result=$?
 return ${result}
+}
+function getArchitecture(){
+  local machine=$(uname -m)
+  case $machine in
+    x86_64|x64)
+      echo x86_64
+      ;;
+    aarch64|arm64)
+      echo aarch64
+      ;;
+    *)
+      log.error "不支持的架构"
+      log.warn "您的CPU为 $(uname -m)"
+      log.warn "请截图以便于开发者适配"
+      returnError
+      ;;
+  esac
 }
